#!/bin/bash
# usb-pam-dispatch.sh — session-aware lock/unlock executor
# Generated by pamusb setup — do not edit manually
#
# Validates that a graphical session exists, resolves DBUS address,
# and executes loginctl lock-session or unlock-session.

ACTION="${1:-}"
USERNAME="${2:-{{USERNAME}}}"
LOG_FILE="/tmp/pamusb-dispatch.log"

ts() { date '+%Y-%m-%d %H:%M:%S'; }

log() {
    printf '%s [dispatch] %s\n' "$(ts)" "$*" >> "$LOG_FILE"
}

log "Called: ACTION=$ACTION USER=$USERNAME"

if [[ -z "$ACTION" ]]; then
    log "ERROR: no action provided"
    exit 1
fi

# Find an active graphical session for the target user
SESSION_ID=""
while IFS= read -r line; do
    sid=$(echo "$line" | awk '{print $1}')
    stype=$(loginctl show-session "$sid" -p Type --value 2>/dev/null)
    sstate=$(loginctl show-session "$sid" -p State --value 2>/dev/null)
    suser=$(loginctl show-session "$sid" -p Name --value 2>/dev/null)

    if [[ "$suser" == "$USERNAME" && ("$stype" == "x11" || "$stype" == "wayland") && "$sstate" == "active" ]]; then
        SESSION_ID="$sid"
        break
    fi
done < <(loginctl list-sessions --no-legend 2>/dev/null)

if [[ -z "$SESSION_ID" ]]; then
    log "No active graphical session found for $USERNAME — skipping"
    exit 0
fi

log "Session: $SESSION_ID (type=$(loginctl show-session "$SESSION_ID" -p Type --value 2>/dev/null))"

case "$ACTION" in
    remove)
        log "Locking session $SESSION_ID"
        loginctl lock-session "$SESSION_ID"
        log "Session locked"
        ;;
    add)
        log "Unlocking session $SESSION_ID"
        loginctl unlock-session "$SESSION_ID"
        log "Session unlocked"
        ;;
    *)
        log "Unknown action: $ACTION"
        exit 1
        ;;
esac
