SHELL := /bin/bash

.PHONY: test check fmt clean

test:
	@bash tests/mail/units.sh

check:
	@bash -n bin/mail

fmt:
	@echo "[skip] no mail rite formatter configured"

clean:
	@echo "[skip] no mail rite cleanup configured"
