#!/usr/bin/env bash

mail_account_file() {
    printf '%s\n' "${SIGILS_MAIL_ACCOUNT_FILE:-$HOME/.config/sigils/mail/accounts.env}"
}

mail_config_home() {
    printf '%s\n' "${XDG_CONFIG_HOME:-$HOME/.config}"
}

mail_maildir_root() {
    printf '%s\n' "${MAIL_MAILDIR_ROOT:-$HOME/Mail}"
}

mail_notmuch_root() {
    printf '%s\n' "${MAIL_NOTMUCH_ROOT:-$(mail_maildir_root)}"
}

mail_account_names() {
    printf '%s\n' "$MAIL_ACCOUNTS" | tr ' ' '\n'
}

mail_account_prefix() {
    local account="$1"
    local normalized

    normalized="${account^^}"
    normalized="${normalized//-/_}"
    printf 'MAIL_%s' "$normalized"
}

mail_account_get() {
    local account="$1"
    local field="$2"
    local var_name

    var_name="$(mail_account_prefix "$account")_${field}"
    printf '%s\n' "${!var_name:-}"
}

mail_urlencode() {
    local input="$1"
    local length="${#input}"
    local index
    local char

    for (( index = 0; index < length; index++ )); do
        char="${input:index:1}"
        case "$char" in
            [a-zA-Z0-9.~_-]) printf '%s' "$char" ;;
            *) printf '%%%02X' "'$char" ;;
        esac
    done
    printf '\n'
}

mail_load_accounts() {
    local account_file

    account_file="$(mail_account_file)"
    [[ -f "$account_file" ]] || {
        echo "error: account file not found: $account_file" >&2
        return 1
    }

    set -a
    # shellcheck disable=SC1090
    source "$account_file"
    set +a

    [[ -n "${MAIL_ACCOUNTS:-}" ]] || {
        echo "error: MAIL_ACCOUNTS is empty in $account_file" >&2
        return 1
    }
}

mail_validate_accounts() {
    local account

    while IFS= read -r account; do
        [[ -n "$account" ]] || continue
        [[ -n "$(mail_account_get "$account" ADDRESS)" ]] || {
            echo "error: missing ADDRESS for account $account" >&2
            return 1
        }
        [[ -n "$(mail_account_get "$account" IMAP_HOST)" ]] || {
            echo "error: missing IMAP_HOST for account $account" >&2
            return 1
        }
        [[ -n "$(mail_account_get "$account" SMTP_HOST)" ]] || {
            echo "error: missing SMTP_HOST for account $account" >&2
            return 1
        }
    done < <(mail_account_names)
}

mail_prepare_directories() {
    local config_home
    local maildir_root
    local account

    config_home="$(mail_config_home)"
    maildir_root="$(mail_maildir_root)"

    mkdir -p "$config_home/aerc" "$(dirname "$(mail_account_file)")" "$maildir_root"

    while IFS= read -r account; do
        [[ -n "$account" ]] || continue
        mkdir -p "$maildir_root/$account"
    done < <(mail_account_names)
}

mail_write_file() {
    local path="$1"
    mkdir -p "$(dirname "$path")"
    cat >"$path"
}

mail_generate_mbsyncrc() {
    local account
    local address
    local imap_host
    local imap_user
    local imap_port
    local maildir_root

    maildir_root="$(mail_maildir_root)"

    {
        printf '# Generated by sigils rite mail setup\n'
        printf 'SyncState *\n\n'

        while IFS= read -r account; do
            [[ -n "$account" ]] || continue
            address="$(mail_account_get "$account" ADDRESS)"
            imap_host="$(mail_account_get "$account" IMAP_HOST)"
            imap_user="$(mail_account_get "$account" IMAP_USER)"
            imap_port="$(mail_account_get "$account" IMAP_PORT)"
            [[ -n "$imap_user" ]] || imap_user="$address"
            [[ -n "$imap_port" ]] || imap_port="993"

            cat <<EOF
IMAPAccount $account-remote
Host $imap_host
Port $imap_port
User $imap_user
PassCmd "pass show mail/$account/imap | head -n 1"
SSLType IMAPS

IMAPStore $account-remote
Account $account-remote

MaildirStore $account-local
SubFolders Verbatim
Path $maildir_root/$account/
Inbox $maildir_root/$account/Inbox

Channel $account
Far :$account-remote:
Near :$account-local:
Patterns *
Create Near
Sync All
Expunge Both

EOF
        done < <(mail_account_names)
    } | mail_write_file "$HOME/.mbsyncrc"
}

mail_generate_aerc_accounts() {
    local account
    local address
    local name
    local smtp_host
    local smtp_user
    local smtp_port
    local maildir_root
    local smtp_uri

    maildir_root="$(mail_maildir_root)"

    {
        printf '# Generated by sigils rite mail setup\n\n'

        while IFS= read -r account; do
            [[ -n "$account" ]] || continue
            address="$(mail_account_get "$account" ADDRESS)"
            name="$(mail_account_get "$account" NAME)"
            smtp_host="$(mail_account_get "$account" SMTP_HOST)"
            smtp_user="$(mail_account_get "$account" SMTP_USER)"
            smtp_port="$(mail_account_get "$account" SMTP_PORT)"
            [[ -n "$smtp_user" ]] || smtp_user="$address"
            [[ -n "$smtp_port" ]] || smtp_port="587"
            [[ -n "$name" ]] || name="$address"
            smtp_uri="smtp+plain://$(mail_urlencode "$smtp_user")@$smtp_host:$smtp_port"

            cat <<EOF
[$account]
source = maildir://$maildir_root/$account
check-mail = 5m
check-mail-cmd = mbsync -a
from = $name <$address>
outgoing = $smtp_uri
outgoing-cred-cmd = pass show mail/$account/smtp | head -n 1
copy-to = Sent
archive = Archive
default = INBOX

EOF
        done < <(mail_account_names)
    } | mail_write_file "$(mail_config_home)/aerc/accounts.conf"
}

mail_generate_msmtprc() {
    local account
    local address
    local smtp_host
    local smtp_user
    local smtp_port

    {
        cat <<'EOF'
# Generated by sigils rite mail setup
defaults
auth on
tls on
port 587
EOF
        printf '\n'

        while IFS= read -r account; do
            [[ -n "$account" ]] || continue
            address="$(mail_account_get "$account" ADDRESS)"
            smtp_host="$(mail_account_get "$account" SMTP_HOST)"
            smtp_user="$(mail_account_get "$account" SMTP_USER)"
            smtp_port="$(mail_account_get "$account" SMTP_PORT)"
            [[ -n "$smtp_user" ]] || smtp_user="$address"
            [[ -n "$smtp_port" ]] || smtp_port="587"

            cat <<EOF
account $account
host $smtp_host
port $smtp_port
from $address
user $smtp_user
passwordeval pass show mail/$account/smtp | head -n 1

EOF
        done < <(mail_account_names)

        printf 'account default : %s\n' "$(printf '%s\n' "$MAIL_ACCOUNTS" | awk '{print $1}')"
    } | mail_write_file "$HOME/.msmtprc"

    chmod 600 "$HOME/.msmtprc"
}

mail_generate_notmuch_config() {
    local primary_account
    local primary_name
    local primary_email
    local extra_emails=()
    local account
    local address

    primary_account="$(printf '%s\n' "$MAIL_ACCOUNTS" | awk '{print $1}')"
    primary_name="$(mail_account_get "$primary_account" NAME)"
    primary_email="$(mail_account_get "$primary_account" ADDRESS)"
    [[ -n "$primary_name" ]] || primary_name="$primary_email"

    while IFS= read -r account; do
        [[ -n "$account" && "$account" != "$primary_account" ]] || continue
        address="$(mail_account_get "$account" ADDRESS)"
        [[ -n "$address" ]] && extra_emails+=("$address")
    done < <(mail_account_names)

    {
        cat <<EOF
[database]
path=$(mail_notmuch_root)

[user]
name=$primary_name
primary_email=$primary_email
other_email=$(IFS=';'; printf '%s' "${extra_emails[*]}")

[new]
tags=inbox;unread;
ignore=

[search]
exclude_tags=deleted;spam;
EOF
    } | mail_write_file "$HOME/.notmuch-config"
}

mail_generate_configs() {
    mail_prepare_directories
    mail_generate_mbsyncrc
    mail_generate_aerc_accounts
    mail_generate_msmtprc
    mail_generate_notmuch_config
}
