#!/bin/bash
# usb-pam-guard.sh — debounce wrapper for USB add/remove udev events
# Generated by usb-auth setup — do not edit manually
#
# Filters rapid duplicate events within a configurable debounce window.
# Delegates actual lock/unlock to usb-pam-dispatch.sh.

ACTION="${1:-}"
USERNAME="{{USERNAME}}"
MAIN_UUID="{{MAIN_UUID}}"
DEBOUNCE_SECONDS=3
LOCK_FILE="/run/usb-pam-guard-${MAIN_UUID}.lock"
LOG_FILE="/tmp/usb-auth-guard.log"

ts() { date '+%Y-%m-%d %H:%M:%S'; }

log() {
    printf '%s [guard] %s\n' "$(ts)" "$*" >> "$LOG_FILE"
}

log "Event: ACTION=$ACTION UUID=$MAIN_UUID"

# Debounce: if a lock file exists and was written within DEBOUNCE_SECONDS, skip
if [[ -f "$LOCK_FILE" ]]; then
    local_mtime=$(stat -c '%Y' "$LOCK_FILE" 2>/dev/null || echo 0)
    now=$(date +%s)
    age=$(( now - local_mtime ))
    if (( age < DEBOUNCE_SECONDS )); then
        log "Debounced (last event ${age}s ago, window=${DEBOUNCE_SECONDS}s)"
        exit 0
    fi
fi

# Record this event
printf '%s\n' "$ACTION" > "$LOCK_FILE"

# Delegate to dispatch script
log "Delegating to dispatch: ACTION=$ACTION USER=$USERNAME"
/usr/local/bin/usb-pam-dispatch.sh "$ACTION" "$USERNAME"
